export const courses = [
  'Administração',
  'Análise e Desenvolvimento de Sistemas',
  'Arquitetura e Urbanismo',
  'Biomedicina',
  'Ciências Contábeis',
  'Direito',
  'Educação Física',
  'Enfermagem',
  'Engenharia Civil',
  'Engenharia de Produção',
  'Farmácia',
  'Fisioterapia',
  'Gastronomia',
  'Medicina',
  'Nutrição',
  'Odontologia',
  'Psicologia',
  'Radiologia',
  'Sistemas de Informação',
];
